server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contestbot
    username: mollen
    password: 929s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

bot:
  username: fhelhockey_bot
  token: 8368777417:AAFwwqL_YB-MiP6wdlnbbBbWoseiv1T-BxA
  webhook-path: https://contestbot.example.com/webhook
  telegram_channels:
    - id: "-1001650728463"
      name_id: "fhelhockey"
      name: "Федерация хоккея | Электросталь"

vk:
  serviceToken: ea00d32eea00d32eea00d32e29e939cd8eeea00ea00d32e82acb916a01c2d062ab49af0
  apiVersion: "5.131"
  groups:
    - id: "fh_electro"
      name: "Федерация Хоккея городского округа Электросталь"