server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contestbot
    username: mollen
    password: 929s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

bot:
  username: elektrostal_test_bot
  token: 8252803793:AAGaPyncrcUAoQirkk4bVJXsFO0-fWZQ_3o
  telegram_channels:
    - id: "-1001650728463"
      name_id: "fhelhockey"
      name: "Федерация хоккея | Электросталь"


vk:
  serviceToken: ea00d32eea00d32eea00d32e29e939cd8eeea00ea00d32e82acb916a01c2d062ab49af0
  apiVersion: "5.131"
  groups:
    - id: "fh_electro"
      name: "Федерация Хоккея городского округа Электросталь"